services:
    mysql:
        image: mysql:8.4
        platform: linux/amd64
        healthcheck:
            test: '/usr/bin/mysql --execute "SHOW databases;"'
            timeout: 3s
            interval: 1s
            retries: 10
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: sylius
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"

volumes:
    mysql-data: