live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: '/_components'

sylius_crud_routes:
    resource: 'sylius.routing.loader.crud_routes_attributes'
    type: service

sylius_routes:
    resource: 'sylius.routing.loader.routes_attributes'
    type: service
