sylius_twig_hooks:
    hooks:
        # Masquer la colonne quantité et récurrence dans le header du panier pour les tokens
        'sylius_shop.cart.index.content.form.sections.general.items.head':
            quantity:
                enabled: false
            recurring:
                enabled: false
                
        # Masquer la quantité et récurrence dans le body du panier pour les tokens  
        'sylius_shop.cart.index.content.form.sections.general.items.body':
            quantity:
                enabled: false
            recurring_settings:
                enabled: false
            # Remplacer le template item par le nôtre pour afficher les tokens proprement
            item:
                template: 'shop/cart/index/content/form/sections/general/items/body/item.html.twig'
                priority: 300
