sylius_twig_hooks:
    hooks:
        # Configuration du header avec brand + navigation + user
        'sylius_shop.base.header.content':
            logo:
                template: 'shop/shared/layout/header/brand_logo.html.twig'
                priority: 300
            main_navigation:
                template: 'shop/shared/layout/header/main_nav.html.twig'
                priority: 210
            wallet_balance:
                template: 'shop/shared/layout/header/wallet_balance.html.twig'
                priority: 150

        # Masquer le message "Hello User!"
        'sylius_shop.base.header.content.security.logged_in_user.desktop':
            welcome_message:
                enabled: false

        # Désactiver le menu des catégories (on a notre navigation custom)
        'sylius_shop.base.header.navbar':
            menu:
                enabled: false
