sylius_twig_hooks:
    hooks:
        # Index page
        'sylius_shop.account.video_generation.index.content':
            breadcrumbs:
                template: 'account/video/generation/index/content/breadcrumbs.html.twig'
                priority: 200
            menu:
                template: '@SyliusShop/account/common/content/menu.html.twig'
                priority: 100

        'sylius_shop.account.video_generation.index.content.main':
            header:
                template: 'account/video/generation/index/content/main/header.html.twig'
                priority: 300
            pagination_top:
                template: 'account/video/generation/index/content/main/pagination.html.twig'
                priority: 200
            grid:
                template: 'account/video/generation/index/content/main/grid.html.twig'
                priority: 100
            pagination_bottom:
                template: 'account/video/generation/index/content/main/pagination.html.twig'
                priority: 0
        
        # Create page
        'sylius_shop.account.video_generation.create.content':
            breadcrumbs:
                template: 'account/video/generation/create/content/breadcrumbs.html.twig'
                priority: 200
            menu:
                template: '@SyliusShop/account/common/content/menu.html.twig'
                priority: 100

        'sylius_shop.account.video_generation.create.content.main':
            header:
                template: 'account/video/generation/create/content/main/header.html.twig'
                priority: 100
            form:
                template: 'account/video/generation/create/content/main/form.html.twig'
                priority: 0
        
        'sylius_shop.account.video_generation.create.content.main.form':
            prompt:
                template: 'account/video/generation/create/content/main/form/prompt.html.twig'
                priority: 300
            tips:
                template: 'account/video/generation/create/content/main/form/tips.html.twig'
                priority: 200
