sylius_grid:
    grids:
        app_admin_wallet_transactions_for_wallet:
            extends: app_admin_wallet_transaction
            driver:
                name: doctrine/orm
                options:
                    class: App\Wallet\Entity\WalletTransaction
                    repository:
                        method: createByObjectIdQueryBuilder
                        arguments:
                            objectId: $id
            fields:
                wallet:
                    type: string
                    enabled: false
            filters:
                customer:
                    type: ux_autocomplete
                    enabled: false
                type:
                    type: select
                    enabled: false
                date:
                    type: date
                    enabled: false
                reference:
                    type: string
                    enabled: false
            actions:
                item: ~
