sylius_grid:
    grids:
        app_admin_wallet:
            driver:
                name: doctrine/orm
                options:
                    class: App\Wallet\Entity\Wallet
            fields:
                id:
                    type: string
                    label: ID
                customer:
                    type: twig
                    label: Client
                    options:
                        template: '@SyliusAdmin/shared/grid/field/customer.html.twig'
                balance:
                    type: string
                    label: app.ui.wallet_balance
            actions:
                item:
                    show:
                        type: show
