parameters:
    # Video generation status check delay (in milliseconds)
    app.video.status_check_delay: 500  # 30 seconds

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Kernel.php}'

    App\Wallet\Payment\CommandHandler\PayWalletCommandHandler:
        arguments:
            $paymentRequestStateMachine: '@state_machine.sylius_payment_request'
            $paymentStateMachine: '@state_machine.sylius_payment'
            $orderCheckoutStateMachine: '@state_machine.sylius_order_checkout'
            $orderStateMachine: '@state_machine.sylius_order'

    # Video Provider - only this needs explicit configuration
    App\IA\Provider\VideoGenerationProviderInterface: '@App\IA\Provider\MockProvider'
    App\IA\Provider\MockProvider: ~

    



    

